server:
  port: 8000

spring:
    application:
        name: test

logging:
    pattern:
        console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %-5level [${spring.application.name}] - [${spring.profiles.active}] - %msg%n'
        file: '%d{dd-MM-yyyy HH:mm:ss.SSS} %-5level [${spring.application.name}] - [${spring.profiles.active}] - %msg%n'

toto:
  url: ${url}
  user: ${user}
  password: ${password}
#-----------
# Properties
#-----------
