server:
  port: 8000

spring:
    profiles:
        active: dev



logging:
  level:
    org.springframework: info
    org.hibernate: info

# ----------
# Parameters
# ----------
# environment: local

# application.id: backend-test

# ## list properties
# categories.types: zone001,zone002,zone003
# #=================

# # AWS Parameter Store
# application:
#   title: Local App Title
# #=================